-- MySQL Script generated by MySQL Workbench
-- Fri Jul 19 11:58:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proyecto` (
  `id_proyecto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `fecha` DATETIME NULL,
  `tipo` VARCHAR(1) NULL,
  PRIMARY KEY (`id_proyecto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`casos_prueba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`casos_prueba` (
  `id_casos_prueba` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(200) NULL,
  `precondiciones` VARCHAR(400) NULL,
  `status` VARCHAR(1) NULL,
  `id_proyecto` INT NOT NULL,
  PRIMARY KEY (`id_casos_prueba`),
  INDEX `fk_casos_prueba_proyecto_idx` (`id_proyecto` ASC) VISIBLE,
  CONSTRAINT `fk_casos_prueba_proyecto`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `mydb`.`proyecto` (`id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalle` (
  `id_detalle` INT NOT NULL AUTO_INCREMENT,
  `accion` VARCHAR(200) NOT NULL,
  `resultado` VARCHAR(200) NOT NULL,
  `id_casos_prueba` INT NOT NULL,
  PRIMARY KEY (`id_detalle`),
  INDEX `fk_detalle_casos_prueba1_idx` (`id_casos_prueba` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_casos_prueba1`
    FOREIGN KEY (`id_casos_prueba`)
    REFERENCES `mydb`.`casos_prueba` (`id_casos_prueba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
